//CHRIS
userData [ anonymous {
    id: 1,
    name: 'Jeremy Leif',
    email: 'jeremy.leif@gmail.com',
    address: '1770 Bryant Ave South, Minneapolis, MN 55403',
    ward: null,
    admin: false },
  anonymous {
    id: 2,
    name: 'Paul Dunkirk',
    email: 'Paul.Dunkirk@gmail.com',
    address: '2120 colfax Ave South, Minneapolis, MN 55405',
    ward: null,
    admin: false },
  anonymous {
    id: 3,
    name: 'Phil Curtis',
    email: 'Phil.Curtis@gmail.com',
    address: '1200 Nicollet Mall APT 309 Minneapolis MN 55403',
    ward: null,
    admin: false },
  anonymous {
    id: 4,
    name: 'Christine pogochick',
    email: 'cpogo@gmail.com',
    address: '929 Portland Ave APT 1211 Minneapolis MN 55404',
    ward: null,
    admin: false },
  anonymous {
    id: 5,
    name: 'Arri Kooiman',
    email: 'arri.kooiman@gmail.com',
    address: '2104 Kenwood Pkwy Minneapolis MN 55405',
    ward: null,
    admin: false },
  anonymous {
    id: 6,
    name: 'john holup',
    email: 'john.holup@gmail.com',
    address: '3052 17th Ave S, Minneapolis, MN 55407',
    ward: null,
    admin: false },
  anonymous {
    id: 7,
    name: 'Kris Jensan',
    email: 'kristine.b.jensen@gmail.com',
    address: '2120 Newton Ave S,Minneapolis, MN 55405',
    ward: null,
    admin: false },
  anonymous {
    id: 8,
    name: 'Chris Staton',
    email: 's.stanton@gmail.com',
    address: '4218 Portland Ave Minneapolis, MN 55407',
    ward: null,
    admin: false },
  anonymous {
    id: 9,
    name: 'donald bagel',
    email: 'dinohunter@gmail.com',
    address: '5119 Camden Ave N,\nMinneapolis, MN 55430',
    ward: null,
    admin: false } ]
//CHRIS
